### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/haskell-ricochet#27]
We should write a lot of test cases and use a CI service for automatic testing on Github.

What should one use to test Haskell applications? Something usable trough `cabal test` I suppose.

**Comment by froozen** [comment]
:+1:
I think using travis would be the best idea, as it integrates well with github.
From my experience with [kademlia](https://github.com/froozen/kademlia), using [QuickCheck](https://hackage.haskell.org/package/QuickCheck) together with [HUnit](https://hackage.haskell.org/package/HUnit) works very well.
I'd also propose we use the [tasty testing framework](http://documentup.com/feuerbach/tasty) because it has realy pretty output.

**Comment by sternenseemann** [comment]
:+1: for tasty, as it also seems to be really nice to use.

**Comment by sternenseemann** [comment]
[Documentation on Test-Suites and cabal](https://www.haskell.org/cabal/users-guide/developing-packages.html#test-suites).

**Comment by sternenseemann** [comment]
[tasty-lens](http://hackage.haskell.org/package/tasty-lens)

**Comment by froozen** [comment]
All tasty-lens does is checking whether the lens laws hold. I'm not sure we need that as long as we generate the lenses using Template Haskell.

**Comment by sternenseemann** [comment]
First tests have been merged, will be expanded in the future, feel free to contribute!
