### ISSUE TITLE
root needed to run the demos

### ISSUE THREAD

**Issue by froozen** [Jugendhackt/haskell-ricochet#43]
I'm not sure if only I have this issue, but I need to run the demos as root, otherwise I'll get the following error:

> server: /var/lib/tor/control_auth_cookie: openBinaryFile: permission denied (Permission denied)

This is quite problematic as users will need root permissions to run anything using `haskell-ricochet`, which makes it damn near worthless.
Any ideas on how to fix this?

**Comment by photm5** [comment]
The [pull request](https://github.com/solatis/haskell-network-anonymous-tor/pull/5) I created over at `network-anonymous-tor` enables us to use NULL instead of COOKIE authentication, which doesn’t require root rights.  The problem is, I didn’t investigate yet whether that’s considered good practise, the COOKIE authentication will probably exist for a good reason.

**Comment by sternenseemann** [comment]
You'd need to change your tor directory to `~/.tor` or similar or run tor as tor user.

**Comment by photm5** [comment]
Even if Tor is run as user `tor`, if he doesn’t run the demos as user `tor`, the demos won’t be able to access the cookie file.  Changing the Tor directory to `~/.tor` doesn’t change the access rights, so that won’t help either.  Switching the user to run the demos as user `tor` will require root permissions too.

The only three options I see:
- Add the user’s user to the `tor` group (Requires root permissions once)
- Run the tor daemon as the user’s user (The C++ implementation does this)
- Using NULL authentication

**Comment by sternenseemann** [comment]
You can run `tor` as user that was what I meant.

**Comment by sternenseemann** [comment]
There are a lot more viable methods to authenticate, like ,he HashedPassword one - also just run tor as a user.
